typedef enum {
	LPC_CONTROL=0,
	LPC_INPUT=1,
	LPC_OUTPUT=2,
	LPC_LATENCY=3,
	LPC_ORDER=4,
	LPC_BUFFER_SIZE=5,
	LPC_WHISPER=6,
	LPC_OLA=7,
	LPC_GLOTTAL=8,
	LPC_PREEMPHASIS=9,
	LPC_PITCH=10,
	LPC_TUNING=11,
	LPC_BEND_RANGE=12
} PortIndex;
